### Register
POST http://localhost:3000/api/v1/auth/register
Content-Type: application/json

{
    "email": "zaki@gmail.com",
    "password": "zaki123"
}

### Login
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
    "email": "zaki@gmail.com",
    "password": "zaki123"
}

### authenticate
GET http://localhost:3000/api/v1/auth/authenticate
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjk5MTc2NDIyfQ.uv27qzfmiD6meVwlJcQ1ueiAEndxf2XLM0W8lmzWIUM