### Register
POST http://localhost:3000/api/v1/auth/register
Content-Type: application/json

{
    "email": "gunawan@gmail.com",
    "password": "gunawan123"
}

### Login
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
    "email": "gunawan@gmail.com",
    "password": "gunawan123"
}

### authenticate
GET http://localhost:3000/api/v1/auth/authenticate
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNjk5MTk1Mzc3fQ._uYKBhh8v1C5YkM-kzytb5VUGIEb_jA1vuZlHwzQWlw